[pytest]
addopts = -k "not test_generate_subgraphs_from_adjacency_matrix and not (test_counts_raises and HomodyneMeasurement)"


markers =
    monkey: marks tests with stochastic inputs.

python_functions = test_* *_benchmark *_script
python_files = test_*.py *_benchmark.py *_script.py
